### ISSUE TITLE
Replacing rbdl Library and Transitioning to Mobile Platform

### ISSUE THREAD

**Issue by SlimeVRX** [Xinyu-Yi/carticulate#1]
I am asking whether the current project involves rewriting a physics simulation library to replace the rbdl library. If I want to use this project instead of rbdl, what steps should I take? Since I’m looking to experiment with running TransPose, PIP, and PNP on mobile devices, I’m encountering issues because the rbdl library isn’t working.

To resolve this, I want to use the this project instead of rbdl, I'll need to adapt or rewrite your project. This would involve changing the project's programming language to one that's compatible with both Android and iOS, rather than continuing with C++.

**Comment by Xinyu-Yi** [comment]
Yes. The `dynamics` folder should contain the codes that can replace rbdl in PNP/PIP. In fact, I rewrite all the dynamic algorithms using generalized pose in SO(3) space and derivatives (angular velocities, accelerations, torques) in so(3) to avoid singularity. But later I find that rbdl already supports this (by using spherical joints). So currently I haven't integrated my codes into PIP/PNP and replaced the rbdl. Later I will do this.

After rewriting the dynamics, I also put some other C++ things in this repo, but they are not needed to run PIP/PNP. If you want to rewrite the physics by yourself, you can check the dynamics folder. But maybe later when I am integrating this into PIP, I will modify some apis or add some additional codes. Another solution is that you can check PIP/PNP later. I will integrate this into PIP/PNP as an alternative choice to rbdl.

**Comment by SlimeVRX** [comment]
Thank you for your prompt response and for the work you've done. I will proceed with the transition and keep you updated on the progress
